name: Docker

# This will run when:
# - when new code is pushed to master to push the tags latest.
# - when a pull request is created and updated  to make sure the
#   Dockerfile is still valid.

# To be able to push to dockerhub, this expects the following
# secrets to be set in the project:
# - DOCKER_HUB_USERNAME : username that can push to the org
# - DOCKER_HUB_PASSWORD : password asscoaited with the username

# To be able to push to github, this expects the following
# secrets to be set in the project:
# - GHCR_USERNAME : username that can push to the org
# - GHCR_PASSWORD : password asscoaited with the username

on:
  push:
    branches:
      - hurricane


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file docker.yml --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA

      
      
